# Generated by Django 4.2.7 on 2023-11-12 09:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_transaction_daily_timepstamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_timepstamp', models.IntegerField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 11, 12, 9, 1, 56, 727452, tzinfo=datetime.timezone.utc))]),
        ),
    ]
