# Generated by Django 4.2.7 on 2023-11-12 10:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_daily_timepstamp_dailycloseprice_daily_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='daily_timepstamp',
            new_name='daily_timestamp',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 11, 12, 10, 14, 24, 795325, tzinfo=datetime.timezone.utc))]),
        ),
    ]
