# Generated by Django 4.2.7 on 2023-11-23 07:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycloseprice',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 11, 23, 7, 43, 32, 422366, tzinfo=datetime.timezone.utc))]),
        ),
    ]
