# Generated by Django 4.2.7 on 2023-11-24 07:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_timestamp_unix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price_at_transaction',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='dailycloseprice',
            name='roi',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 11, 24, 7, 44, 39, 541128, tzinfo=datetime.timezone.utc))]),
        ),
    ]
