# Generated by Django 4.2.7 on 2023-12-04 15:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_transaction_timestamp_portfoliometrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliometrics',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 12, 4, 15, 36, 24, 872808, tzinfo=datetime.timezone.utc))]),
        ),
    ]
