# Generated by Django 4.2.7 on 2023-12-06 06:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliometrics',
            name='max_roi',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='portfoliometrics',
            name='min_roi',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 12, 6, 6, 55, 43, 992725, tzinfo=datetime.timezone.utc))]),
        ),
    ]
