# Generated by Django 4.2.7 on 2023-12-12 18:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_transaction_amount_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliometrics',
            name='BTC_amount',
            field=models.DecimalField(decimal_places=8, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliometrics',
            name='USD_invested',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliometrics',
            name='average_price',
            field=models.DecimalField(decimal_places=2, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliometrics',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.portfolio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=32, validators=[django.core.validators.MinValueValidator(1e-07), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='initial_value',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2010, 7, 17, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2023, 12, 12, 18, 12, 34, 747510, tzinfo=datetime.timezone.utc))]),
        ),
    ]
