# Generated by Django 4.2.7 on 2024-05-22 17:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_transaction_amount_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2010, 7, 18, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2024, 2, 28, 0, 0, tzinfo=datetime.timezone.utc))]),
        ),
    ]
