# Generated by Django 4.2.7 on 2025-01-19 16:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_transaction_daily_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='daily_timestamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2010, 7, 18, 0, 0, tzinfo=datetime.timezone.utc)), django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2025, 1, 18, 0, 0, tzinfo=datetime.timezone.utc))]),
        ),
    ]
