# Generated by Django 4.2.7 on 2025-02-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSDHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_unix', models.BigIntegerField()),
                ('time', models.DateTimeField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('volumefrom', models.FloatField()),
                ('volumeto', models.FloatField()),
                ('close', models.FloatField()),
            ],
        ),
    ]
