# Generated by Django 4.2.7 on 2025-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcusdhourly',
            name='time_unix',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
