# Generated by Django 4.2.7 on 2025-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_btcusdhourly_time_unix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btcusdhourly',
            old_name='time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='btcusdhourly',
            old_name='time_unix',
            new_name='date_time_unix',
        ),
    ]
